version: "3.9"
services:
  api:
    build: .
    ports:
      - "8000:8000"
    restart: unless-stopped
  web:
    image: python:3.11-slim
    working_dir: /web
    volumes:
      - ./web:/web:ro
    command: python -m http.server 8080
    ports:
      - "8080:8080"
    restart: unless-stopped


